---
title: "Effort Report - Sample"
output: html_document
---

``` {r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
<<<<<<< HEAD
source('effort.functions.R')
=======
>>>>>>> ac82f60e51a933aa2f20e47bff487abf9997243c
```

``` {r}
# importing data
d <- read.csv('sample.effort.csv')

# report based on student id number - this will be automated for mail out
student.id <- 1000

# Get full name based on student.id
student.name <- "Jen Eric"
```

```{r}

<<<<<<< HEAD
=======
effortPlot.bysubject <- function(d) {
  # Recieves a long data frame and returns a ggplot historgram
  # Their must be the following fields:
  #  -- Score : The score (1 to 5, 5 being Outstanding)
  #  -- Subject : The subject (such as 'English')
  #  -- Source : Either Student or Teacher
  #  -- Category : One of Diligence, Behaviour or Effort
  require(ggplot2)
  
  # Setting up reording of subjects -- this needs to be refined 
  # to include Y12 subjects
  slist <- c("English",
             "Mathematics",
             "Science",
             "History",
             "Geography",
             "Cornerstone",
             "Music",
             "French",
             "Design & Technology",
             "Media Technology",
             "Food Technology",
             "Grahpics Technology",
             "Visual Art",
             "PDHPE")
  subject.orders <- data.frame(Subject = slist, Order = seq(length(slist)))
  d <- merge(d, subject.orders)
  forOrder <- unique(data.frame(Subject = d$Subject, Order = d$Order))
  forOrder <- forOrder[order(forOrder$Order),]
  facetOrder <- forOrder$Subject
  d$Subject <- factor(d$Subject, levels = facetOrder)
  
  d$Category <- factor(d$Category, levels = c("Diligence", "Engagement", "Behaviour"))
  
  # Creating the actual plot
  g <- ggplot(data = d, 
              aes(x = Category, y = Score, fill = Source)) + 
    geom_bar(stat = "identity", position = "dodge", width = 0.6) +
    facet_grid(Subject ~ .) +
    scale_y_discrete(name = "Effort rating", 
                     limits = c("Unsatisfactory", "Fair", "Good", "Very Good", "Outstanding")) +
    scale_fill_brewer(palette = "Paired", type = "div")
  return(g)
}
>>>>>>> ac82f60e51a933aa2f20e47bff487abf9997243c
```


### Effort report for `r student.name`
<<<<<<< HEAD
``` {r fig.height = 4, fig.width = 7}
d <- d[d$Student.ID == student.id,]
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(plotly))
overall <- overallEffortPlot(d)
overall
```

\nbsp

``` {r fig.height = 7, fig.width = 7}
d <- d[d$Student.ID == student.id,]
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(plotly))
breakdown <- effortPlot(d, "Effort by Subject")
breakdown
```
=======


``` {r}
d <- d[d$Student.ID == student.id,]
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(plotly))
suppressMessages(ggplotly(effortPlot.bysubject(d)))
```
>>>>>>> ac82f60e51a933aa2f20e47bff487abf9997243c
