---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressWarnings(suppressPackageStartupMessages(library(ggplot2)))
```


``` {r}
# getting the all important graphing functions
#source(effort.functions.R)

effortPlot <- function(d, ctitle = "Chart title") {
  # Recieves a long data frame and returns a ggplot historgram
  # Their must be the following fields:
  #  -- Score : The score (1 to 5, 5 being Outstanding)
  #  -- Subject : The subject (such as 'English')
  #  -- Source : Either Student or Teacher
  #  -- Category : One of Diligence, Behaviour or Effort
  require(ggplot2)
  # Setting up reording of subjects - more may need to be added as the system is run
  slist <- c("English","English Standard", "English Advanced", "English Extension 1", "English Extension 2",
             "Mathematics", "Mathematics General", "Mathematics Extension 1", "Mathematics Extension 2",
             "Science", "Biology", "Chemistry", "Physics",
             "History", "History Ancient", "History Modern", "History Extension",
             "Geography", "Economics", "Legal Studies", "Business Studies",
             "Cornerstone",
             "Music", "Music 1 & 2",
             "French", "French Continuers",
             "Design and Technology", "Design & Technology", "Engineering Studies",
             "Media Technology",
             "Food Technology",
             "Grahpics Technology",
             "Visual Arts",
             "Drama",
             "PDHPE",
             "Distance Education", "TVET")
  subject.orders <- data.frame(Subject = slist, Order = seq(length(slist)))
  d <- merge(d, subject.orders)
  forOrder <- unique(data.frame(Subject = d$Subject, Order = d$Order))
  forOrder <- forOrder[order(forOrder$Order),]
  facetOrder <- forOrder$Subject
  d$Subject <- factor(d$Subject, levels = facetOrder)
  
  d$Category <- factor(d$Category, levels = c("Diligence", "Engagement", "Behaviour"))
  
  # Creating the actual plot
  g <- ggplot(data = d, 
              aes(x = Category, y = Score, fill = Source)) + 
    geom_bar(stat = "identity", position = "dodge", width = 0.6) +
    ggtitle(ctitle) +
    guides(fill = guide_legend(title = NULL)) +
    theme(text = element_text(size = 10)) +
    facet_grid(Subject ~ .) +
    coord_cartesian(ylim = c(1,5)) +
    scale_y_discrete(name = "Effort rating", 
                     limits = c("Unsatisfactory", "Fair", "Good", "Very Good", "Outstanding")) +
    scale_fill_manual(values = c("skyblue","navy"))
  return(g)
}

overallEffortPlot <- function(d, ctitle = "Overall Effort") {
  require(dplyr)
  d <- summarise(group_by(d, Source, Category), mean(Score))
  names(d) <- c("Source", "Category", "Score")
  d$Category <- factor(d$Category, levels = c("Diligence", "Engagement", "Behaviour"))
  # creating the plot
  g <- ggplot(data = d, aes(x = Category, y = Score, fill = Source)) +
    geom_bar(stat = "identity", position = "dodge", width = 0.6) +
    ggtitle(ctitle) +
    guides(fill = guide_legend(title = NULL)) +
    theme(text = element_text(size = 10)) +
    coord_cartesian(ylim = c(1,5)) +
    scale_y_discrete(name = "Effort rating", 
                     limits = c("Unsatisfactory", "Fair", "Good", "Very Good", "Outstanding")) +
    scale_fill_manual(values = c("skyblue","navy"))
  return(g)
}

# ID is the student code from effort_report_script.R
df <- effort.data[effort.data$Student.code == ID,]
student.name <- student.info[student.info$Student.code == ID,]$Student.name
```
### Effort report for `r student.name`

``` {r fig.height = 4, fig.width = 8}
overallEffortPlot(df)
```

``` {r fig.height = 13, fig.width = 8}
effortPlot(df, ctitle = "Effort by Subject")
```