---
output: 
  pdf_document:
    latex_engine: xelatex
sansfont: Gill Sans
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
suppressWarnings(suppressPackageStartupMessages(library(ggplot2)))
```

``` {r}
# getting the all important graphing functions
source('effort.functions.R')
df <- effort.data[effort.data$Teacher.code == tcode,]
```


``` {r fig.env='marginfigure', fig.height = 1, fig.width = 1}
# Adding the Oxley logo
logo <- png::readPNG("images/oxleycrest.png")
grid::grid.raster(logo)
```

# `r tcode` Effort Report - Term 2 2018

``` {r fig.height = 3, fig.width = 8}
suppressWarnings(overallEffortPlot(df))
```

&nbsp;

&nbsp;

``` {r fig.height = 3, fig.width = 8}
df.gender <- merge(df, student.info[,c("Student.code","Gender")], all.x = T)
df.gender <- df.gender[complete.cases(df.gender),]
df.gender$Category <- factor(df.gender$Category, level = c("Diligence","Engagement","Behaviour"))
g.gender <- ggplot(data = df.gender) +
  geom_density(aes(x = Score, colour = Gender, linetype = Source), bw = 1) +
  facet_grid(Gender ~ Category) + ggtitle("Comparison by category and gender")
g.gender + ggthemes::theme_tufte()
```

``` {r fig.height = 20, fig.width = 8}
classes <- unique(df$Class.code)
for (class in classes) {
  print(suppressWarnings(effortPlotClass(df[df$Class.code == class,], title = class)))
}
```
